# Generated by Django 3.2.16 on 2022-12-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studenteventtask',
            options={'verbose_name': 'StudentEventTask', 'verbose_name_plural': '003 Academics Student Event Task'},
        ),
        migrations.AlterModelOptions(
            name='studenteventtaskanswer',
            options={'verbose_name': 'StudentEventTaskAnswer', 'verbose_name_plural': '004 Academics Student Event Task Answer'},
        ),
    ]
