# Generated by Django 3.2.16 on 2022-12-08 05:34

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Code')),
                ('code_en_us', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Code')),
                ('code_ja', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Code')),
                ('code_ar', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Code')),
                ('code_ko', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Code')),
                ('code_hi', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Code')),
                ('code_es', models.CharField(db_index=True, max_length=255, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('name_en_us', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ja', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ko', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_hi', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_es', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('description_en_us', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('description_ja', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('description_ar', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('description_ko', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('description_hi', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('description_es', models.TextField(blank=True, help_text='Course Description, Maximum 500 KBytes.', null=True, verbose_name='Description')),
                ('order_no', models.IntegerField(default=0, help_text='Course ordered.', verbose_name='Order No')),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': '001 Master Courses',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('name_en_us', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ja', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ar', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_ko', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_hi', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('name_es', models.CharField(db_index=True, max_length=255, null=True, verbose_name='Name')),
                ('typed', models.CharField(choices=[('01', 'Single-choice'), ('02', 'Multiple-choice')], db_index=True, max_length=2, verbose_name='Typed')),
                ('detailed', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('detailed_en_us', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('detailed_ja', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('detailed_ar', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('detailed_ko', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('detailed_hi', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('detailed_es', models.TextField(blank=True, help_text='Detail Task, Maximum 500 KBytes.', null=True, verbose_name='Detail Task')),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.course', verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': '002 Master Tasks',
                'unique_together': {('course', 'typed', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('code', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, verbose_name='Code')),
                ('code_en_us', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, null=True, verbose_name='Code')),
                ('code_ja', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, null=True, verbose_name='Code')),
                ('code_ar', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, null=True, verbose_name='Code')),
                ('code_ko', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, null=True, verbose_name='Code')),
                ('code_hi', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, null=True, verbose_name='Code')),
                ('code_es', models.CharField(db_index=True, help_text='Option answer signed.', max_length=255, null=True, verbose_name='Code')),
                ('option', models.CharField(choices=[('', 'Multiple-choice'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], db_index=True, max_length=1, verbose_name='Option')),
                ('detailed', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('detailed_en_us', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('detailed_ja', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('detailed_ar', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('detailed_ko', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('detailed_hi', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('detailed_es', models.TextField(blank=True, help_text='Detail Answer, Maximum 500 KBytes.', null=True, verbose_name='Detail Answer')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Is Correct Answer?')),
                ('user_update', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='masters.task', verbose_name='Task')),
            ],
            options={
                'verbose_name': 'Answer',
                'verbose_name_plural': '003 Master Answers',
                'unique_together': {('task', 'code')},
            },
        ),
    ]
